### ISSUE TITLE
Firefox 89 issues

### ISSUE THREAD

**Issue by l3ony2k** [not-holar/my_firefox_theme#10]
I've been using this custom theme for about two months now and I really love it. But it's buggy after Firefox updated version 89. Really hope the developer can update this.

**Comment by not-holar** [comment]
Turns out i haven't restarted my browser for days, had no idea an update came out 😅. I'll get right to fixing everything

**Comment by l3ony2k** [comment]
That's awesome! Thanks a lot!

**Comment by not-holar** [comment]
Should be fixed by c1a34639b0a238e0cf80c195336fac1a678b7d8d
