### ISSUE TITLE
No numbers are displayed in urlbar

### ISSUE THREAD

**Issue by Dakla** [not-holar/my_firefox_theme#2]
This line hide numbers in urlbar if dont install Open Sans font
`font-family: 'Google Sans', 'Open Sans', 'Noto Sans', 'Twemoji Mozilla', 'Twitter Emoji Color', 'Segoe UI Emoji';`

**Comment by not-holar** [comment]
well this is weird

**Comment by not-holar** [comment]
https://github.com/not-holar/my_firefox_theme/commit/68068530c3d50ee2351219c0ec8ecd31d7ad31bd should fix this
